services:
    mitmproxy:
        image: mitmproxy/mitmproxy:8.1.1
        volumes:
            - ./scripts:/scripts
        ports:
            - "8080:8080"
            - "8081:8081"
        command: [ "mitmweb", "--verbose", "-s", "/scripts/flow-counter.py", "--web-host", "0.0.0.0", "--mode", "reverse:http://prometheus:9090" ]                
        networks:
            - overlay
        depends_on:
            - prometheus


