version: 1
root:
  level: DEBUG
  handlers: ['console']
formatters:
  json:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      class: pythonjsonlogger.jsonlogger.JsonFormatter
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: json
loggers:
  requests.packages.urllib3:
    level: DEBUG    
  rpiclient:
    level: DEBUG  
  rpiclient.send:
    level: DEBUG    
